title: Paula Mendez
logo: /assets/img/logo.png
email: dev dot paulamendez at gmail dot com
description: DevOps Engineer. AWS + Python. 26 years old. 
show_downloads: false
google_analytics: G-WB8Y8SW22J
color-scheme: dark
favicon: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: San Diego, CA
    icon: <i class="fa-solid fa-location-dot"></i>
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/paulamendez1/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/paulipotter
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://paulipotter.github.io/blog.html
  - name: Resume
    icon: <i class="fa-solid fa-file-arrow-down"></i>
    link: /MendezResume.pdf

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
